SCMOD-4072: Updated to use latest dropwizard
CAFDataProcessing/worker-document pull request #27
Opened 2018-05-22 20:13 UTC by Anthony-McGreevy

2018-05-22 20:14 UTC, Anthony-McGreevy commented
**TEST BUILD:** http://sou-jenkins2.hpeswlab.net/job/CAFDataProcessing/view/Developer/job/CAFDataProcessing~worker-document~SCMOD-4072-testbuild~CI/

2018-05-22 23:35 UTC, dermot-hardy requested changes

2018-05-22 23:35 UTC, dermot-hardy commented on pom.xml
> +    Copyright 2018-2017 EntIT Software LLC, a Micro Focus company.
Project inception year should remain 2015.

2018-05-23 10:57 UTC, Anthony-McGreevy commented
@dermot-hardy Inception year has been updated

2018-05-23 11:38 UTC, dermot-hardy requested changes
- Version number needs rolled on
- Release notes need updated

2018-05-23 11:52 UTC, Anthony-McGreevy commented
@dermot-hardy version and release notes updated.

2018-05-23 11:53 UTC, dermot-hardy approved these changes

2018-05-23 11:59 UTC, merged